### ISSUE TITLE
Correção - Botões Voltar

### ISSUE THREAD

**Issue by Ligadonasaude-IgorSiqueira** [Ligadonasaude-PedroIvo/ligadonasaude#33]
Todos os botões Voltar das ferramentas devem ser alterados para DashBoard .
Verificar todos os nomes da ferramentas no portal e normalizar em toda a paginas,texto,títulos,pop ip,modal e etc.

Adcionar um botão encerrar Encerrar sessão na intranet,somente nela.

**Comment by Ligadonasaude-IgorSiqueira** [comment]
Arquivos para atualização:

Views
C:\wamp64\www\ligadonasaude\modules\system\chat\views\index.frm.php
C:\wamp64\www\ligadonasaude\modules\system\contact\views\index.frm.php
C:\wamp64\www\ligadonasaude\modules\system\messages\views\index.frm.php

**Comment by Ligadonasaude-GabrielPinho** [comment]
Verificar botão Dashboard nas ferramentas de Procura e Oferta. @

**Comment by Ligadonasaude-GabrielPinho** [comment]
Finalizado teste ok
