### ISSUE TITLE
Correção - Tela de Termos de Uso

### ISSUE THREAD

**Issue by Ligadonasaude-IgorSiqueira** [Ligadonasaude-PedroIvo/ligadonasaude#44]
![image](https://cloud.githubusercontent.com/assets/24610974/23903533/9902d0ae-08a3-11e7-9ad6-df3e3bb86410.png)

Sem realizar o primeiro post aparece a mensagem descrita acima,ela deve aparecer somente se ocorrer post

**Comment by Ligadonasaude-GabrielPinho** [comment]
Testado. Ok.
