### ISSUE TITLE
Correção -  Tools sem Login

### ISSUE THREAD

**Issue by Ligadonasaude-IgorSiqueira** [Ligadonasaude-PedroIvo/ligadonasaude#51]
Alterar o nome da ferramenta nos tools sem a realização do login

![image](https://cloud.githubusercontent.com/assets/24610974/23905767/de01ea76-08aa-11e7-87d0-7bcfb2dbacb7.png)

**Comment by Ligadonasaude-IgorSiqueira** [comment]
Concluído
Arquivos para Atualizar

Views
C:\wamp64\www\ligadonasaude\modules\site\index\views\

**Comment by Ligadonasaude-GabrielPinho** [comment]
Testado. Está ok.
