### ISSUE TITLE
Correção -  LS-Mensagem

### ISSUE THREAD

**Issue by Ligadonasaude-IgorSiqueira** [Ligadonasaude-PedroIvo/ligadonasaude#58]
Adcionar um botão de Responder do lado do deletar em menssagem.

![image](https://cloud.githubusercontent.com/assets/24610974/23913619/52af8b96-08c2-11e7-80c2-bf86b62c44a5.png)

**Comment by Ligadonasaude-GabrielPinho** [comment]
Testado.OK.
