### ISSUE TITLE
Correção -Login e Termos

### ISSUE THREAD

**Issue by Ligadonasaude-IgorSiqueira** [Ligadonasaude-PedroIvo/ligadonasaude#74]
Ao acessar o portal pela primeira vez se o cara ja tiver aceitado os termos no cadastro não  ira aparecer a tela atual.

Enviar codigo via sms no  online não está funcionando!.

O botão voltar na tela de codigo deve virar cancelar e deletar usuário pré-criado

**Comment by Ligadonasaude-GabrielPinho** [comment]
Testado. Ok
