### ISSUE TITLE
Correção - LS.AskMe

### ISSUE THREAD

**Issue by Ligadonasaude-PedroIvo** [Ligadonasaude-PedroIvo/ligadonasaude#84]
1°Erro abaixo
![image](https://cloud.githubusercontent.com/assets/24388380/23999896/787f2c7e-0a38-11e7-9751-1f0d423f9566.png)

**Comment by Ligadonasaude-IgorSiqueira** [comment]
O erro ocorre devido a uma sintaxe incorreta no model do objeto.

Para corrigir:

Model:
C:\wamp64\www\ligadonasaude\models\Question.mdl.php
